config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'reader#show'

  resources :feeds, only: %i[index new create edit update destroy]
  resource :reader, only: :show, controller: 'reader'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/feed.rb
# frozen_string_literal: true

class Feed < ApplicationRecord
  scope :default_order, -> { order(created_at: :desc) }
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/feeds_controller.rb
# frozen_string_literal: true

class FeedsController < ApplicationController
  before_action :set_feed, only: %i[edit update destroy]

  respond_to :html

  def index
    @feeds = Feed.default_order.page(params[:page]).per(20)
  end

  def new
    @feed_form = FeedForm.new
  end

  def create
    @feed_form = FeedForm.new

    if @feed_form.perform(feed_params)
      redirect_to feeds_path, notice: 'Feed created'
    else
      flash.now[:alert] = 'Url should lead to an RSS feed'
      render :new
    end
  end

  def edit
    @feed_form = FeedForm.new(@feed)
  end

  def update
    @feed_form = FeedForm.new(@feed)

    if @feed_form.perform(feed_params)
      redirect_to feeds_path, notice: 'Feed updated'
    else
      render :edit, alert: @feed.errors.messages.first
    end
  end

  def destroy
    if @feed.destroy
      redirect_to feeds_path, notice: 'Feed deleted'
    else
      redirect_to feeds_path, alert: 'Could not delete Feed'
    end
  end

  private

  def set_feed
    @feed = Feed.find(params[:id])
  end

  def feed_params
    params.require(:feed).permit(:url)
  end
end

app/controllers/reader_controller.rb
class ReaderController < ApplicationController
  def show
    @posts = Kaminari.paginate_array(FetchPostsService.perform).page(params[:page]).per(20)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def flash_messages
    %w(notice alert).
      select { |type| flash.key?(type) }.
      map { |type| flash_block(type) }.
      join
  end

  private

  def flash_block(type)
    flash_classes = { notice: 'alert alert-success', alert: 'alert alert-danger' }

    content_tag(:div, class: flash_classes[type.to_sym]) do
      content_tag("button", "×", class: 'close clear', "data-dismiss" => "alert") + flash[type.to_sym]
    end
  end
end

app/views/feeds/_feed.html.slim
tr
  td = feed.title
  td = feed.url
  td
    .btn-group
      = link_to edit_feed_path(feed), class: 'btn btn-success mr-1' do
          i.fas.fa-pencil-alt
      = link_to feed, method: :delete, class: 'btn btn-danger ml-1', data: { confirm: 'Are you sure?' } do
          i.fas.fa-trash

app/views/feeds/_form.html.slim
= simple_form_for @feed_form,
  url: (@feed_form.persisted? ? feed_path(@feed) : feeds_path),
  as: :feed, html: { class: 'form-horizontal inputs-sm input-form' } do |f|
  .form-group
    = f.input :title, input_html: { disabled: true, class: 'form-control'}
  .form-group
    = f.input :url, input_html: { class: 'form-control'}, required: true

  .row
    .col-sm-offset-3.col-sm-9
      = f.button :submit, class: 'btn-primary', value: 'Save'
      = link_to "Cancel", feeds_path, class: 'btn btn-primary ml-2'

      - if @feed_form.persisted?
        = link_to 'Delete', @feed_form.feed,
          method: :delete,
          data: { confirm: "Are you sure you want to delete this feed?" },
          class: "btn btn-danger ml-2"

app/views/feeds/edit.html.slim
.tasks_page
  h3 Edit Feed
  br
  = render "form"

app/views/feeds/index.html.slim
.feeds_page
  h3 Feeds
  .toolbar
    = link_to 'Add a new Feed', new_feed_path, class: 'btn btn-success'

  table.table.table-bordered.table-striped.mt-3
    thead
      tr
        th Title
        th Url
        th

    tbody
      = render @feeds if @feeds

  br
  = paginate @feeds, theme: 'twitter-bootstrap-4'

app/views/feeds/new.html.slim
.feeds_page
  h3 Edit Feed
  br
  .d-flex.justify-content-center
    = render 'form'

app/views/layouts/application.html.slim
doctype html
html lang="en"
  head
    meta charset="utf-8"
    meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1"
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    title
      = @head_title or "RSS reader"
    = yield(:head)
    = csrf_meta_tags
    = stylesheet_link_tag "application", :media => "all"
    = javascript_include_tag "application"

  body
    = render 'shared/main_menu'

    .container-fluid.mt-3
      .row
        .col-sm-12
          - unless flash.blank?
            = raw flash_messages
      .row
        .col-md-12
          = yield
      .footer.col-md-12

app/views/reader/show.html.slim
- colors = %w(#df494e #68a5b7 #8f978e #d8b6ad #677b94 #677b94 #66be98 #fcd06d #f8a427 #d42b14)

.col-md-8
  h1.border-bottom.border-gray.pb-2.mb-0 Recent Posts

  br
  = paginate @posts, theme: 'twitter-bootstrap-4'

  - @posts.each do |post|
    div.media.mt-3.border-bottom
      svg.placeholder-img
        title Placeholder
        rect.placeholder-rect fill=colors.sample
      div.media-text
        = link_to post.link, class: 'title-text', target: '_blank' do
          - post.title
        div.mt-2 #{post.description.html_safe}

  br
  = paginate @posts, theme: 'twitter-bootstrap-4'

app/views/shared/_main_menu.html.slim
nav.navbar.navbar-expand-lg.navbar-dark.bg-dark.sticky-top
  .navbar-brand Rss
  button.navbar-toggler type='button' data-toggle="collapse" data-target='#navbarNavDropdown' aria-controls='navbarNavDropdown' aria-expanded='false' aria-label='Toggle navigation'
    span.navbar-toggler-icon
  #navbarNavDropdown.collapse.navbar-collapse
    ul.navbar-nav
      li.nav-item = link_to 'Feeds', feeds_path, class: 'nav-link'
      li.nav-item = link_to 'Reader', reader_path, class: 'nav-link'